# BotBot Configuration override file
!Config

    BOT: !Config
        PREFIX: "(bb)"
        INTENTS:
            guilds: yes
            members: yes
            bans: yes
            emojis: yes
            integrations: yes
            webhooks: yes
            invites: yes
            voice_states: yes
            presences: yes
            messages: yes
            reactions: yes
            typing: yes

    DATABASE: !Config
        APPLICATION_NAME: 'BotBot'

    LOGGING: !Config
        LOG_LEVEL: "WARNING"

    EXTENSIONS:

        # Core Extensions
        cogs.core.command_stats: ~
        cogs.core.whitelist: ~

        # Logging extensions
        cogs.logging.logging: ~
        cogs.logging.status: ~
        cogs.logging.voice: ~    

        # Meme extensions
        cogs.memes.bottom: ~        
        cogs.memes.markov: ~
        cogs.memes.timecard: ~
        cogs.memes.status: ~

        # Game Extensions
        # cogs.games.tangrams: ~
        cogs.games.pokemon: ~
        cogs.games.connect_four: ~
        cogs.games.boggle: ~
        cogs.games.foggle: ~
        cogs.games.minesweeper: ~

        # General Extensions
        cogs.reminders: ~
        
        # Moderation Extensions
        # moderation.logs: ~
        cogs.moderation.spam: ~
        cogs.moderation.tools: ~

    SECRET_EXTENSIONS: !ENV SECRET_EXTENSIONS
    REPOSITORY_URL: https://github.com/bijij/BotBot

    # Consts
    DPY_VOICE_GENERAL: !Channel 336642139381301249 741656304359178271
    DISCORD_PY: !Guild 336642139381301249
