# Bot Configuration File
!Config

    BOT: !Config
        PREFIX: !ENV BOT_PREFIX
        TOKEN: !ENV BOT_TOKEN

    DATABASE: !Config
        USERNAME: !ENV DB_USERNAME
        PASSWORD: !ENV DB_PASSWORD
        DATABASE: !ENV DB_DATABASE

    LOGGING: !Config
        LOG_LEVEL: "INFO"
        LOG_LEVEL_ALL: "ERROR"
        LOG_TO_FILE: true
        WEBHOOK: !ENV "LOGGING_WEBHOOK"

    EXTENSIONS:
        jishaku: ~

        cogs.core.admin: ~
        cogs.core.meta: ~
        cogs.core.stats: ~
        cogs.core.info: ~

        cogs.logging.logging: ~
        cogs.logging.status: ~
        cogs.logging.voice: ~    

        cogs.memes.bottom: ~        
        cogs.memes.markov: ~
        cogs.memes.timecard: ~
        cogs.memes.status: ~

        # cogs.games.tangrams: ~
        # cogs.games.pokemon: ~

        cogs.reminders: ~
        
        # moderation.logs: ~
        cogs.moderation.spam: ~
        cogs.moderation.tools: ~

    SECRET_EXTENSIONS: !ENV SECRET_EXTENSIONS

    REPOSITORY_URL: https://github.com/bijij/BotBot
