# Bot Configuration File
!Config

    BOT: !Config
        PREFIX: !ENV BOT_PREFIX
        TOKEN: !ENV BOT_TOKEN

    DATABASE: !Config
        USERNAME: !ENV DB_USERNAME
        PASSWORD: !ENV DB_PASSWORD
        DATABASE: !ENV DB_DATABASE

    LOGGING: !Config
        LOG_LEVEL: "INFO"
        LOG_LEVEL_ALL: "ERROR"
        LOG_TO_FILE: true
        WEBHOOK: !ENV "LOGGING_WEBHOOK"

    EXTENSIONS:
        core.admin: ~
        core.meta: ~
        core.stats: ~
        core.info: ~

        logging.logging: ~
        logging.status: ~        
        
        memes.markov: ~
        memes.timecard: ~

        reminders: ~
        pokemon: ~
        moderation: ~

    SECRET_EXTENSIONS: !ENV SECRET_EXTENSIONS

    REPOSITORY_URL: https://github.com/bijij/BotBot
