[tool.poetry]
name = "botbot"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.19.2"
pillow = "^7.2.0"
websockets = "^8.1"
markovify = "^0.8.3"
donphan = "^2.4.1"
dateparser = "^0.7.6"
ampharos = {git = "https://github.com/bijij/Ampharos.git"}
discord-ext-menus = {git = "https://github.com/rapptz/discord-ext-menus.git"}
humanize = {git = "https://github.com/jmoiron/humanize.git"}
discord-ext-alternatives = {git = "https://github.com/ext-creators/discord-ext-alternatives.git"}
"discord.py" = "^1.5.0"
"backports.zoneinfo" = "^0.2.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
